name: Upsert Strava pages

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upsert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/requirements.txt
      - name: Run script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
        run: |
          python ./scripts/strava.py ./content/strava
      - name: Commit new or modified pages
        run: |
          git add ./content/strava
          git config --global user.email "github-actions[bot]@users.noreply.github.com "
          git config --global user.name "GitHub Actions bot"
          git commit -m "Add/update Strava pages"
          git push origin
